version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      PHCONFIG_FILE: /run/secrets/phconfig.py
    restart: always
    secrets:
      - phconfig.py

secrets:
  phconfig.py:
    file: phconfig.py
